### ISSUE TITLE
I wanna work on the Android version of this app .

### ISSUE THREAD

**Issue by heysagnik** [AureliaApps/KyoNeoPublic#6]
Can I?

**Comment by rainyskye** [comment]
@Aeastr 

Any comments on this for now?

**Comment by pmnlla** [comment]
I doubt that an android version is coming soon, and what little I do know about it I can't publicly disclose.
However, if help is needed, we'll certainly post about it in the appropriate channels.

Let's wait for Aether's response for now.

**Comment by Aeastr** [comment]
Unfortunately, at this time, we cannot disclose any information about the Android version of the app. As the code is closed-source, we are unable to accept contributions to the Android version. Therefore, we will have to close this issue for now. However, we highly appreciate your interest in the app and welcome any feedback you may have.
