### ISSUE TITLE
Visual Representation of Time

### ISSUE THREAD

**Issue by Soft-Bred** [AureliaApps/KyoNeoPublic#7]
**Is your feature request related to a problem? Please describe.**
It is not easily identifiable how long an event is other than having to calculate the time between the start of the event and the end of the event.

**Describe the solution you'd like**
Would like for the heights of the events blocks to be directly proportional to the length of the event and the length of the events to be visualised both via height and also a label indicating how long the event is. For example if a event was an hour long it will be x-height and also have a label that indicates "1 hour long". If it is two hours long it would be 2x-height and also specify that it is two hours long.

There's something similar to what calendars do where they indicate the length of the event by increasing the height.

**Describe alternatives you've considered**
None

**Additional context**
<img width="240" alt="004046@2x" src="https://user-images.githubusercontent.com/60551230/236045068-c4cb86cb-29e4-4b40-b910-2ae3c6da12a9.png">

**Comment by pmnlla** [comment]
To be implemented in a future build, see [this](https://t.me/c/1908075467/342).
